device:
  pin_hash: 03ac674216f3e15c761ee1a5e255f067953623c8b388b4459e13f978d7c846f4
  pin_length: 4
  version: 0.0.1
  image_folders:
    - boot_images
device_backend:
  place_holder: text
flash_mode:
  active: false
  auto_start: false
info:
  last_checked: '2025-03-27 11:13:30'
  last_update: '2025-03-27 14:12:03'
  local_ip: 192.168.200.150
mount_mode:
  auto_start: false
touch_gui:
  auto_start: true
  device_backend_script: ../device_backend/main.py
  colors:
    dark: '#322f29'
    light: '#d7d4cc'
    mid: '#7d7a73'
    transparent: '#ff00ff'
  fps: 60
  res_height: 120
  res_width: 200
  title: Variable Boot Device Touch GUI
wap:
  auto_start: false
web_if:
  api:
    auto_start: true
    device_backend_script: ../../device_backend/main.py
    keepalive: 2
    max_requests: 500
    max_requests_jitter: 50
    port: 12413
    threads: 2
    timeout: 60
    worker_class: gthread
    workers: 5
  client:
    active: true
    auto_start: true
    keepalive: 2
    max_requests: 500
    max_requests_jitter: 50
    port: 56666
    threads: 2
    timeout: 60
    worker_class: gthread
    workers: 5
